template-file-path: ./template.yaml
parameters:
  EnvironmentName: ecs-lab
  VpcCIDR: 10.0.0.0/16
  PublicSubnet1CIDR: 10.0.1.0/24
  PublicSubnet2CIDR: 10.0.2.0/24
  PrivateSubnet1CIDR: 10.0.3.0/24
  PrivateSubnet2CIDR: 10.0.4.0/24
  RepositoryName: ecs-lab-app
  GitHubOrg: basit-devBE
  AppRepoName: ecs-app
  AppRepoBranch: master
  CodeStarConnectionArn: arn:aws:codeconnections:eu-central-1:124355645722:connection/460f4052-2bd6-4ff3-a029-9255e1059b65
  HealthCheckPath: /actuator/health
  ContainerPort: 8080
  Cpu: '256'
  Memory: '512'
  BootstrapRepositoryName: ecs-lab-bootstrap
  BootstrapImageTag: latest
  S3PrefixListId: pl-6ea54007
tags:
  Project: ecs-cicd-lab
  ManagedBy: cloudformation-gitsync
  Environment: production
